theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag

navigation:
  - title: "Introduction"
    url: /prueba_io/introduction.html
  - title: "Chapter 1"
    url: /prueba_io/chapter1.html
  - title: "Chapter 2"
    url: /prueba_io/chapter2.html
