theme: jekyll-theme-cayman

navigation:
  - title: "Introduction"
    url: /prueba_io/introduction
  - title: "Chapter 1"
    url: /prueba_io/chapter1
  - title: "Chapter 2"
    url: /prueba_io/chapter2
