theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag

navigation:
  - title: "Introduction"
    url: /prueba_io/introduction.md
  - title: "Chapter 1"
    url: /prueba_io/chapter1.md
  - title: "Chapter 2"
    url: /prueba_io/chapter2.md
